name: Transcribe
on:
  issues:
    types:
      - opened

jobs:
  build:
    name: Run transcription
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3

      - name: Check if already transcribed
        id: check
        shell: bash
        run: |
          PREVIOUS=$( gh search issues "${{ github.event.issue.body }}" --repo artpi/transcribe --json url -L 1 | jq -r ".[0].url" )
          if [ PREVIOUS != null ] ; then
            echo ::set-output name=continue::false
            gh issue comment $ISSUE -b "That video has been already transcribed. $PREVIOUS"
            gh issue close $ISSUE
          else
            echo ::set-output name=continue::true
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE: ${{ github.event.issue.html_url }}

      - run: gh issue comment $ISSUE --body "Running transcription, this may take a while."
        if: ${{ steps.check.outputs.continue }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE: ${{ github.event.issue.html_url }}

